spring:
    application:
        name: springboot-community-dev-proj
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
        generate-ddl: false
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        hikari:
            driver-class-name: org.h2.Driver
            jdbc-url: jdbc:h2:mem:testDB
            username: sa
            password:
            pool-name: H2Pool
            minimum-idle: 1
            maximum-pool-size: 5
            connection-timeout: 10000
            validation-timeout: 5000
            idle-timeout: 600000
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            encoding: UTF-8

#spring:
#    application:
#        name: springboot-community-dev-proj
#    profiles:
#        active: dev
#    jpa:
#        hibernate:
#            ddl-auto: none
#        defer-datasource-initialization: true
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQLDialect
#                format_sql: true
#        generate-ddl: true
#        show-sql: true
#        database-platform: org.hibernate.dialect.MariaDBDialect
#    datasource:
#        hikari:
#            driver-class-name: com.mysql.cj.jdbc.Driver
#            jdbc-url: jdbc:mysql://localhost:3306/springboot
#            username: root
#            password:
#            pool-name: MySQLPool
#            minimum-idle: 1
#            maximum-pool-size: 5
#            connection-timeout: 10000
#            validation-timeout: 5000
#            idle-timeout: 600000
#    sql:
#        init:
#            encoding: UTF-8