config:
    type: aws-parameterstore:/mysql/

spring:
    config:
        import: ${config.type}
    application:
        name: springboot-community-dev-proj
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: validate
        defer-datasource-initialization: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        generate-ddl: true
        show-sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect
    datasource:
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: ${jdbc.url:jdbc:mysql://localhost:8082/springboot}
            username: ${username:root}
            password: ${password:root}
            pool-name: MySQLPool
            minimum-idle: 1
            maximum-pool-size: 5
            connection-timeout: 10000
            validation-timeout: 5000
            idle-timeout: 600000
    sql:
        init:
            encoding: UTF-8
logging:
    config: classpath:logback-config.xml
    level:
        org.springframework.security: DEBUG
server:
    error:
        include-message: on_param